---
title: "CarbonPrice"
output:
  pdf_document:
  html_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = T, fig.path='figures/')
library(magrittr)

options(stringsAsFactors = T)
```


```{r price2,dev='tikz', eval = T}
funcprice = function(s, c0, s0, f){
  c0/(f*s)*((s/s0)^(1/f))
}


cols = c('green', 'grey10', 'red', 'blue')
c0s = c(15)
s0s = c(60)
fs = c(0.8,0.5,0.2)
ymax = 0.6

par(cex = 1.1, mgp=c(2,1,0))
lwds = 2

slinst = c(10^seq(-16,0,0.5) ,seq(2, 110, 1))

for(c0 in c0s){
for(s0 in s0s){
  plot(slinst, funcprice(slinst, c0, s0, fs[1]), col = cols[1], type = 'l', 
       xlim = c(0, max(slinst)), ylim = c(0,ymax),
       xlab = "Post-tx outstanding token supply $s$",
       ylab = "Token price $P(s)$",
       bty = 'l', lwd = lwds)
  for(i in 2:length(fs)){
    lines(slinst, funcprice(slinst, c0, s0, fs[i]), col = cols[i], lwd = lwds)
  }
  abline(v = s0, lwd = 4, lty = 2)
  text(x = s0+0.5, y = ymax,
       labels = paste0('Pre-tx\noutstanding\ntoken supply\n$s_0=',s0,'$'),
       xpd = T, adj = c(0,0))
  text(x = 0, y = ymax, 
       labels = paste0('Pre-tx stablecoin reserve\n$C_0=',c0,'$'),
       xpd = T, adj = c(0,0))
}
}

legend('bottomright', col = cols, title = 'Stablecoin\nreserve\nfraction $F$', lty = 1, legend = paste0('$', fs, '$'), bty = 'n', xpd = T, lwd = lwds, title.adj = 1)

```


```{r price,dev='tikz', eval = F}
funcprice = function(s, c0, s0, f){
  c0/(f*s)*((s/s0)^(1/f))
}


cols = c('green', 'grey10', 'red', 'blue')
c0s = c(5, 15, 25)
s0s = c(90, 60, 30)
fs = c(0.9, 0.5, 
       # 0.2, 
       0.1)
ymax = 0.6

par(cex = 1.8, mgp=c(2,1,0))
lwds = 2

slinst = c(10^seq(-16,0,0.5) ,seq(2, 110, 1))

for(c0 in c0s){
for(s0 in s0s){
  plot(slinst, funcprice(slinst, c0, s0, fs[1]), col = cols[1], type = 'l', 
       xlim = c(0, max(slinst)), ylim = c(0,ymax),
       xlab = "Post-tx outstanding token supply $s$",
       ylab = "Token price $P(s)$",
       bty = 'l', lwd = lwds)
  for(i in 2:length(fs)){
    lines(slinst, funcprice(slinst, c0, s0, fs[i]), col = cols[i], lwd = lwds)
  }
  abline(v = s0, lwd = 4, lty = 2)
  text(x = s0+0.5, y = ymax,
       labels = paste0('$s_0=',s0,'$'),
       xpd = T, adj = c(0,0.5))
  text(x = 0, y = ymax, 
       labels = paste0('Pre-tx stablecoin reserve\n$c_0=',c0,'$'),
       xpd = T, adj = c(0,0))
}
}
legend('bottom', col = 'black', title = 'Pre-tx\noutstanding\ntoken\nsupply $s_0$', lty = 2, lwd = 4,  legend = NA, bty = 'n', xpd = T,  title.adj = 1)


legend('bottomright', col = cols, title = 'Stablecoin\nresearve\nfraction $f$', lty = 1, legend = paste0('$', fs, '$'), bty = 'n', xpd = T, lwd = lwds, title.adj = 1)

```
